import AppKit
import SwiftUI
import UniformTypeIdentifiers

/// Clipboard history. Polls the change count - the only mechanism macOS
/// offers - at a rate that is free in CPU terms, and honours the community
/// markers apps use to say "do not record this".
@MainActor
@Observable
final class ClipboardStore {
    static let shared = ClipboardStore()

    struct Entry: Identifiable, Equatable {
        enum Payload: Equatable {
            case text(String)
            case image(NSImage)
            case files([URL])
        }

        let id = UUID()
        var payload: Payload
        var date: Date
        var sourceApp: String?

        var preview: String {
            switch payload {
            case .text(let text): text.trimmingCharacters(in: .whitespacesAndNewlines)
            case .image: "Image"
            case .files(let urls): urls.map(\.lastPathComponent).joined(separator: ", ")
            }
        }

        var symbolName: String {
            switch payload {
            case .text(let text): text.hasPrefix("http") ? "link" : "text.alignleft"
            case .image: "photo"
            case .files: "doc"
            }
        }
    }

    private(set) var entries: [Entry] = []
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private let limit = 60

    private init() {}

    func start() {
        guard Preferences.shared.clipboardEnabled, timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer?.tolerance = 0.2
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Password managers and similar mark their clips; never store those.
        let types = pasteboard.types ?? []
        let markers: Set<String> = ["org.nspasteboard.TransientType",
                                    "org.nspasteboard.ConcealedType",
                                    "org.nspasteboard.AutoGeneratedType",
                                    "com.agilebits.onepassword"]
        guard !types.contains(where: { markers.contains($0.rawValue) }) else { return }

        let source = NSWorkspace.shared.frontmostApplication?.localizedName

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                             options: [.urlReadingFileURLsOnly: true]) as? [URL],
           urls.isEmpty == false {
            insert(Entry(payload: .files(urls), date: .now, sourceApp: source))
            return
        }
        if let text = pasteboard.string(forType: .string),
           text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == false {
            insert(Entry(payload: .text(text), date: .now, sourceApp: source))
            return
        }
        if let data = pasteboard.data(forType: .tiff) ?? pasteboard.data(forType: .png),
           let image = NSImage(data: data) {
            insert(Entry(payload: .image(image), date: .now, sourceApp: source))
        }
    }

    private func insert(_ entry: Entry) {
        if let existing = entries.first, existing.payload == entry.payload { return }
        withAnimation(Motion.content) {
            entries.insert(entry, at: 0)
            if entries.count > limit { entries.removeLast(entries.count - limit) }
        }
    }

    func copy(_ entry: Entry) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch entry.payload {
        case .text(let text): pasteboard.setString(text, forType: .string)
        case .image(let image): pasteboard.writeObjects([image])
        case .files(let urls): pasteboard.writeObjects(urls.map { $0 as NSURL })
        }
        lastChangeCount = pasteboard.changeCount
        Haptics.success()
    }

    func remove(_ entry: Entry) {
        withAnimation(Motion.content) { entries.removeAll { $0.id == entry.id } }
    }

    func clear() {
        withAnimation(Motion.content) { entries.removeAll() }
    }
}
